const required = (value, field) => { if (!value || !String(value).trim()) throw new Error(`${field} is required`); };
const dateOf = (value, field) => { const date = new Date(value); if (Number.isNaN(date.valueOf())) throw new Error(`${field} must be a valid timestamp`); return date; };
export class RevocationAssuranceService {
  constructor(state = { orders: [], audit: [] }, persist = () => {}, now = () => new Date()) { this.state = { orders: state.orders ?? [], audit: state.audit ?? [] }; this.persist = persist; this.now = now; }
  id(prefix, list) { return `${prefix}-${list.length + 1}`; }
  event(orderId, action, actor, detail = '') { this.state.audit.push({ id: this.id('audit', this.state.audit), orderId, action, actor, detail, at: this.now().toISOString() }); }
  save() { this.persist(this.state); }
  order(input) { for (const field of ['evidenceId', 'requester', 'verifier', 'subject', 'scope', 'dueAt']) required(input[field], field); const dueAt = dateOf(input.dueAt, 'dueAt'); if (dueAt <= this.now()) throw new Error('dueAt must be in the future'); const item = { id: this.id('revocation', this.state.orders), ...input, dueAt: dueAt.toISOString(), status: 'ordered', verification: null, escalation: null }; this.state.orders.push(item); this.event(item.id, 'ordered', input.requester, `${input.subject}:${input.scope}`); this.save(); return item; }
  find(id) { const item = this.state.orders.find((candidate) => candidate.id === id); if (!item) throw new Error('revocation order not found'); return item; }
  capture(id, actor, evidenceReference) { const item = this.find(id); required(actor, 'actor'); required(evidenceReference, 'evidenceReference'); if (item.status !== 'ordered') throw new Error('only ordered revocations can capture evidence'); if (item.requester !== actor) throw new Error('only the requester can capture revocation evidence'); item.status = 'evidence-captured'; item.verification = { evidenceReference, submittedBy: actor, confirmed: false }; this.event(id, 'evidence-captured', actor, evidenceReference); this.save(); return item; }
  verify(id, actor, verdict, note) { const item = this.find(id); required(actor, 'actor'); required(note, 'note'); if (!['confirmed', 'rejected'].includes(verdict)) throw new Error('verdict must be confirmed or rejected'); if (item.status !== 'evidence-captured') throw new Error('only captured evidence can be verified'); if (item.verifier !== actor) throw new Error('only the assigned verifier can confirm revocation'); item.status = verdict === 'confirmed' ? 'verified' : 'rework-required'; item.verification.confirmed = verdict === 'confirmed'; item.verification.note = note; this.event(id, verdict === 'confirmed' ? 'verified' : 'rejected', actor, note); this.save(); return item; }
  escalateDue(actor = 'system') { const now = this.now(); const items = this.state.orders.filter((item) => ['ordered', 'evidence-captured', 'rework-required'].includes(item.status) && dateOf(item.dueAt, 'dueAt') <= now); for (const item of items) { item.escalation = { actor, at: now.toISOString() }; this.event(item.id, 'overdue-escalated', actor, item.status); } if (items.length) this.save(); return items; }
  close(id, actor) { const item = this.find(id); required(actor, 'actor'); if (item.requester !== actor) throw new Error('only the requester can close a revocation order'); if (item.status !== 'verified') throw new Error('only verified revocations can be closed'); item.status = 'closed'; this.event(id, 'closed', actor, item.scope); this.save(); return item; }
  auditFor(id) { this.find(id); return this.state.audit.filter((event) => event.orderId === id); }
}

